### ISSUE TITLE
How build?

### ISSUE THREAD

**Issue by Legnatbird** [RayvaxLux1206/RVL-More-Ores-Fabric-1.20.6#1]
Title

**Comment by Legnatbird** [comment]
Im trying to built, but get this error with current build:
Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config more-ores.client.mixins.json for mod more-ores
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config more-ores.client.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 4 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'more-ores.client.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 7 more
